version: "3.4"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: build
    command: ["yarn", "start:dev"]
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
     - redis
  redis:
    image: redis:7.0.5-alpine
    restart: "no"
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
volumes:
  postgres:
